name: Push to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  push-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure and Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          python -m pip install --upgrade huggingface-hub
          echo $HF_TOKEN | huggingface-cli login
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add space https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME
          git push space main || (git branch -M main && git push -f space main)