name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin "https://$HF_TOKEN@huggingface.co/spaces/jatinmehra/CRAWL-GPT-CHAT"
          git push origin main || (git branch -M main && git push -f origin main)