name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add space https://jatinmehra:$HF_TOKEN@huggingface.co/spaces/jatinmehra/CRAWL-GPT-CHAT
          git push space main || (git branch -M main && git push -f space main)